baseurl = "http://example.org"
title = "WITA"
theme = "dimension"
languageCode = "de-de"
defaultContentLanguage = "de"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[-->Wirtschaftsinformatik Technologien und Anwendungen - Aufgabenzettel 2	<!--]--><br />'
  logo = "fa-diamond"
  copyright = "Untitled"

[languages.de]
languageName = "Deutsch"
weight = 1
title = "GIB GAS WITA Sommersemester 2020"
description = '<!--[-->Wirtschaftsinformatik Technologien und Anwendungen - Aufgabenzettel 2 von Meng Zhang 514831 Ziwei Weng 500177 <!--]--><br />'
